### ISSUE TITLE
Add support for monorepos with direct imports

### ISSUE THREAD

**Issue by jiri-bajer** [gauge-sh/tach#103]
I use a Python monorepo with many scripts, libraries and many microservices (and their number grows over time), where all Python modules are directly importable from Git repository root without any need of packaging/editable installation:

```
bin/
    __init__.py
    script1.py
    script2.py
    ...
lib/
    __init__.py
    library1/
        __init__.py
    library2/
        __init__.py
        module1.py
        module2.py
    ...
svc/
    __init__.py
    service1/
        __init__.py
    service2/
        __init__.py
        module1.py
        module2.py
    ...
```

Rules:
- Libraries can be imported by libraries, scripts and services
- Services cannot be imported by other services
- Scripts cannot be imported
- Only public symbols can be imported when crossing a boundary of a library/service

How can I configure `tach` to setup the import rule enforcement **without the need for a reconfiguration when a service/library is added**?

I think I'd need a support for glob patterns in `path` and `depends_on` + support for import from siblings and parents:

```
modules:
- path: lib/**
  depends_on:
  - lib/**
  strict: true
  siblings: true
  parents: true
- path: svc/**
  depends_on:
  - lib/**
  strict: true
  siblings: true
  parents: true
```

Glob patterns would avoid the need for manual specification of individual modules/packages and their dependencies.
Siblings would allow imports from the same filesystem folder.
Parents would allow imports from modules located in parent filesystem folders.

Would it make sense to add support for such scenario? Or is already there a way how to achieve it?

**Comment by emdoyle** [comment]
Thanks for raising this @jiri-bajer ! I really appreciate the detail, and this brings up some pretty central decisions for the project.
First, you're right that today, Tach would need you to register each new service as a module in order to enforce this architecture. If you were to drop the requirement that services cannot import from each other, Tach would be able to support a 'coarser' structure by wrapping `svc` itself as a module.

For Tach to support this use case though, I think your suggestions make sense, but there are some other things to consider:
- how should `tach mod` handle glob pattern modules? should it indicate things like `siblings` and `parents`?
- are `siblings` and `parents` sufficient to control dependencies within a given glob pattern module? should the 'root' of a service or library determine implicit internal boundaries? (e.g. library1, library2 being treated as pseudo-modules within their glob pattern module)
- when using depends_on with a glob pattern, how should Tach determine whether `strict` should apply? e.g. what if I define a strict module at `lib/**` and then for a different module, add a dependency on `lib/library*`?
- can I define glob pattern dependencies arbitrarily or do they need to match defined modules?
- can I define a glob pattern module, and then also define a module for a path which would match the glob pattern? How do their attributes compose?

I don't think these are intractable, but it does mean that supporting these first few 'abstract' features on top of the existing module system will need to be done carefully.

What do you think of a structure like:
```
modules:
- path: bin
  depends_on:
  - lib
  - svc
- type: container
  id: library
  paths:
  - lib/{library}  # this might be templated, but at minimum would indicate a 'depth' of 1 for this module definition
  siblings: true  # this naming could be improved, implication would be 'all members can import from each other'
- type: container
  id: services
  paths:
  - svc/{service}
  depends_on:
  - library
  siblings: false
```

The central idea is to make the difference between glob pattern modules and 'regular' modules explicit. It adds the 'id' key to allow them to be referenced in `depends_on` as well. The way that the 'container' modules would generally work is:
- for each path in `paths`, each match of the path template is added to the module tree, inheriting the `depends_on` key of the container (with the possibility of extension if the specific match is later referenced in `modules`)
- path templates would explicitly have a templated section to clarify how members of the module are determined. each unique match of the templated section would be considered its own module.
- `siblings` or some similar key would indicate whether all modules in the container should be able to freely depend on each other. this still seems a bit too 'special-case' to me, but I don't have a more composable solution for dependencies that are internal to the container, this would probably be clarified by seeing more use cases

I want to gather more feedback from you and other folks before committing to a decision, but generally want to try something out quickly (on the order of ~1 week). Let me know your thoughts!

**Comment by jiri-bajer** [comment]
Thank you for the consideration!

In the meantime I wrote a simple Python script on top of AST parsing that finds 1st-party imports for a Python module:
```python
def get_first_party_imports(module_path: pathlib.Path) -> tuple[set[str], set[str]]:
    """Get imports from `lib` and `svc` used in a Python module at given filesystem path."""
    imports = set()

    with open(module_path) as source_file:
        contents = source_file.read()

    for node in ast.walk(ast.parse(contents)):
        if isinstance(node, ast.Import):
            imports |= {name.name for name in node.names}
        if isinstance(node, ast.ImportFrom) and node.module:
            imports.add(node.module)

    return {module for module in imports if module.startswith("lib.")}, {
        module for module in imports if module.startswith("svc.")
    }
```
and added a bit of filesystem traversal to scan the whole monorepo -- or to scan only file paths provided via command-line (which is necessary for pre-commit hook).

The script can be easily used as a pre-commit hook:
```yaml
  - repo: local
    hooks:
    - id: check-imports
      name: import directions
      entry: bin/check_imports.py
      language: system
      types: [file, python]
```

This helped me to realize that maybe I don't need a Rust-based, ready-to-use solution and can live with a small (less than 100 LOC), single-purpose, homegrown tool.
