### ISSUE TITLE
Support module "visibility"

### ISSUE THREAD

**Issue by imsut** [gauge-sh/tach#119]
I am working on a Python project that has the exact same problem described [here](https://gauge-sh.github.io/tach/why-tach/#the-problem). We also have a homemade tool similar to (and less mature than) Tach.

One thing our tool supports and Tach does not is "module visibility".
When developers add a module, they could express "This module can be imported only in module X and Y (or any module in package Z)" with our custom tool.
This feature is inspired by "[target visibility rule in Bazel](https://bazel.build/concepts/visibility)"

I wonder if it is possible for Tack to support this feature.

**Comment by emdoyle** [comment]
Hi @imsut ! Thanks for raising this.

If I understand correctly, in addition to declaring dependencies like:
```
- path: module.a
  depends_on:
  - module.b
- path: module.c
  depends_on:
  - module.b
```

You want to also be able to declare 'allowed usage' from the source module outward. So something like:
```
- path: module.b
  visibility:
  - module.a
  - module.c
- path: module.a
  depends_on:
  - module.b
- path: module.c
  depends_on:
  - module.b
# this one would not be allowed
- path: module.d
  depends_on:
  - module.b
```

Is that right? In that case, I think this could be implemented, but it would really just be used to validate the rest of your explicit dependencies. Could you describe the use case for this a bit more?

**Comment by imsut** [comment]
Thank you for the comment @emdoyle 

One use case is to limit access to a private package/module of a larger package.
Let's say I have a calculator package `my.calculator` that exposes public API and another package `my.calculator.impl` that defines functions/classes that are not intended open to public.

I want to say something like this.

```
- path: my.calculator
  depends_on:
  - my.calculator.impl
- path: my.calculator.impl
  visibility:
  - my.calculator
- path: module.a # this is fine.
  depends_on:
    - my.calculator
- path: module.b # this is illegal.
  depends_on:
    - my.calculator.impl
```

Please let me know if this makes sense.

**Comment by emdoyle** [comment]
I think this makes sense. It seems like this would function mostly like guardrails for future changes to your modules. In other words it stops someone from simply running `tach sync` and introducing a dependency on something internal.

However, the example you gave suggests that [strict mode](https://gauge-sh.github.io/tach/strict-mode/) might be a better fit.

More specifically in your case, you'd have:
```
- path: my.calculator
  strict: true  # note strict mode is enabled here
- path: module.a
  depends_on:
  - my.calculator
```

with the key difference being in the public interface of `my.calculator`:

```python
# In my/calculator/__init__.py

from my.calculator.impl import ConcreteCalculator

def calculate(x: int, y: int) -> int:
    return ConcreteCalculator.sum(x, y)


__all__ = ["calculate"]  # this defines the public interface of the module
```

Since the module is in [strict mode](https://gauge-sh.github.io/tach/strict-mode/), you would get the following behavior:

```python
# In module/a.py

from my.calculator import calculate  # this is OK

from my.calculator import ConcreteCalculator  # this will FAIL in 'tach check'
```

Does this cover your use case, or is visibility important beyond this functionality?
