### ISSUE TITLE
Move '<root>' module to the bottom/end of modules in tach.yml

### ISSUE THREAD

**Issue by emdoyle** [gauge-sh/tach#127]
The implicit root boundary appears in the `modules` list in `tach.yml` with the path:  `<root>`

Right now, when this module exists, it is always at the beginning of the `modules` list (sorted lexicographically). This is not ideal, because as a reader (especially a new user), the meaning of `<root>` is hard to parse before first seeing the rest of the modules. This is because a reasonable definition of the root boundary is the 'leftover' code - any code which is not covered by another module.

Given this, it is easier to read the explicit modules first, and then see the 'leftovers' at the end of the file. Tach should explicitly sort this module last when writing the project config to yml.

**Comment by buddhiraz** [comment]
I have just pushed one to fix this arrangement, plz revieew . I havent added description in the PR yet.

**Comment by dhananjaypai08** [comment]
Can you give me an example use case of what the tach.yml might look before and after this enhancement

**Comment by emdoyle** [comment]
@dhananjaypai08 sure! here is an example. I have removed a lot of extra content so that it is easier to read, but the only real difference is that right now, the `<root>` module (if it exists) appears first, and it should instead appear last.

```
modules:
- path: <root>  # root module is first
  depends_on:
  - tach.filesystem
- path: tach.check
  depends_on:
  - <root>
  - tach.errors
  - tach.filesystem
  - tach.parsing
  strict: true
- path: tach.cli
  depends_on:
  - <root>
  - tach.check
  strict: true
...
```

```
modules:
- path: tach.check
  depends_on:
  - <root>
  - tach.errors
  - tach.filesystem
  - tach.parsing
  strict: true
- path: tach.cli
  depends_on:
  - <root>
  - tach.check
  strict: true
- path: <root>  # root module should be last
  depends_on:
  - tach.filesystem
...
```
