### ISSUE TITLE
unify report-external and report interfaces

### ISSUE THREAD

**Issue by fraser-langton** [gauge-sh/tach#385]
### My use case
I have a common directory full of internal packages - these are being managed by [uv](https://docs.astral.sh/uv/)
So I have a pyproject in each package (ie `common/packagename`) 

```toml
[project]
name = "api_models"
version = "0.0.1"
requires-python = "==3.8.*"
dependencies = [
    # external
    "pydantic==2.*",

    # common (internal)
    "blueprinter",
    "database",
    "mapbox",
    "respawned_models",
    "utils",
]

[tool.setuptools.packages.find]
exclude = ["*"]
```

#### Checking dependencies 
Maybe I just made the package and want to just get all the dependencies

I can get there using `tach report-external common/api_models --raw` and `tach report common/api_models` and putting the output into [chatgpt](https://chatgpt.com/share/6719d158-0744-800b-949c-451b1efc0bef) (this is awesome already btw thank you 🫶) however it's a little finnicky 

#### Linting dependencies
I want to check that no one has inadvertently started using a package (internal or external) if it hasn't been declared in the packages dependencies 

At the moment, not immediately possible, nor immediately obvious (which internal apis to use)

### Improvements
- report-external and report should accept the same cli args/options and output the same format for those args/options
- or just unify into a single cli command?
- expose parts of the python api to be used - ie if I wanted to write a pre-commit to check the project matches reality
