### ISSUE TITLE
`tach check-external` reports `python` as unused dependency for poetry projects

### ISSUE THREAD

**Issue by zed** [gauge-sh/tach#441]
```toml
[tool.poetry.dependencies]
python = "^3.11"
```
in `pyproject.toml` leads to:

```shell
% poetry run tach check-external
⚠️  Unused dependencies from project at 'pyproject.toml':
        python

Remove the unused dependencies from the corresponding pyproject.toml file, or consider ignoring the dependencies by adding them to the 'external.exclude' list in tach.toml.
```
