### ISSUE TITLE
`tach-ignore` comments don't work on non-top level imports

### ISSUE THREAD

**Issue by DetachHead** [gauge-sh/tach#515]
in this example, the `tach-ignore` comment on the top-level import works, but the one inside `foo` does not
```toml
# tach.toml

[[modules]]
path = "foo"
depends_on = []
```

```py
# foo/main.py

# tach-ignore
from bar import bar


def foo():
    # tach-ignore
    from bar import bar
```
```
Dependency Errors:
❌  foo\main.py[L9]: Cannot import 'bar.bar'. Module 'foo' cannot depend on '<root>'.
```
