### ISSUE TITLE
`unused_ignore_directives` doesn't work on stdlib/3rd party imports

### ISSUE THREAD

**Issue by DetachHead** [gauge-sh/tach#518]
```toml
# tach.toml
[rules]
unused_ignore_directives = "error"
```
```py
# tach-ignore
from typing import Iterable
```
```
> tach check
✅ All modules validated!
```

**Comment by DetachHead** [comment]
i guess fixing this would need to account for `tach-ignore` comments that are intended for `tach check-external` rather than `tach check`

**Comment by DetachHead** [comment]
maybe `tach check-external` can instead be part of `tach check` which can be enabled or disabled using a rule, (like with `unused_ignore_directives`):

```toml
# tach.toml
[rules]
check_external = true
```

i imagine doing this would also address https://github.com/gauge-sh/tach-vscode/issues/17
