### ISSUE TITLE
`unused_ignore_directives` doesn't work when no import is present

### ISSUE THREAD

**Issue by DetachHead** [gauge-sh/tach#519]
```toml
# tach.toml
[rules]
unused_ignore_directives = "error"
```
```py
# tach-ignore
foo = 1
```
```
> tach check
✅ All modules validated!
```

this is something that could happen easily if using tools like ruff that automatically remove unused imports.
