### ISSUE TITLE
`unused_ignore_directives` does not detect redundant `tach-ignore` comments

### ISSUE THREAD

**Issue by DetachHead** [gauge-sh/tach#520]
```toml
# tach.toml
[rules]
unused_ignore_directives = "error"

[[modules]]
path = "main"
depends_on = []
```
```py
# main/a.py

# tach-ignore
from utilities import foo # tach-ignore
```
```
> tach check
✅ All modules validated!
```

it should report one of the ignore comments as unused because it's redundant
