### ISSUE TITLE
adding `_typeshed` to `external.excludes` no longer works

### ISSUE THREAD

**Issue by DetachHead** [gauge-sh/tach#580]
when the fake `_typeshed` module is added to `external.exclude`, `tach check-external` seems to still report usages of it:
```toml
# tach.toml
[external]
exclude = [
  "_typeshed", # fake TYPE_CHECKING only module that doesn't exist at runtime
]
```
```
>tach check-external
❌: Undeclared dependencies in 'foo.py':
        _typeshed
```
this seems to have been caused by a recent update, since this used to work on 0.20.0. interestingly this only seems to happen with the `_typeshed` module, but other modules in the `exclude` list are correctly ignored
