### ISSUE TITLE
option to ban imports by glob pattern

### ISSUE THREAD

**Issue by DetachHead** [gauge-sh/tach#584]
in my project i want to ban importing from pytest files, which are named like `test_*.py`.

as far as i know there's no way to do this with tach. something like this would be nice:

```toml
[[modules]]
path = "foo"
banned_imports = [
    "**/test_*.py"
]
```

an alternative approach would be to have all test code in a `tests` package and ensure that nothing can import from it:

```toml
[[modules]]
path = "tests"
depends_on = ["foo"]

[[modules]]
path = "foo"
depends_on = []
```
but that won't prevent test files importing from each other:

```py
# tests/test_a.py
from tests.test_b import something # should be an error
```

**Comment by emdoyle** [comment]
@DetachHead thanks for your patience on this issue. I am close to merging #629 , which will allow defining modules with 'module path' glob patterns like this:

```toml
[[modules]]
path = "tests.**"
depends_on = ["foo"]

[[modules]]
path = "foo"
depends_on = []
```

In the case above, the `tests.**` definition will expand dynamically to match all modules with paths beginning with `tests` (you can use `tests.*` to match exactly one level instead). This means that they will each have `depends_on = ["foo"]` and will _not_ be allowed to import from each other.

Would this work for you?

**Comment by DetachHead** [comment]
i think that will work, thanks!

**Comment by emdoyle** [comment]
@DetachHead Could you let me know if you get the behavior you're looking for using globs in `0.26.0`?

Globs as shown in my previous message are now allowed in `path`/`paths` and `depends_on`. Also, you can redefine/shadow a module which is matched by a glob by defining the module as a literal, as long as it appears _after_ the glob.

**Comment by DetachHead** [comment]
thanks! i'm having trouble configuring it to only allow imports from modules that don't start with   `test_` though. i think i need to do something like this:

```toml
[[modules]]
path = "foo"
banned_imports = [
    "**.!test_*"
]
```
though i'm not even sure if that's valid glob syntax
