### ISSUE TITLE
`tach-ignore` comments for `tach check` on multi-line imports trigger "Ignore directive is unused." errors on `tach check-external

### ISSUE THREAD

**Issue by DetachHead** [gauge-sh/tach#604]
```toml
# tach.toml
[[modules]]
path = "foo"
depends_on = []
[[modules]]
path = "baz"
depends_on = []
```

in my project i have some `# tach-ignore` comments above multi-line imports:

```py
# baz/qux.py

# tach-ignore
from foo import (
    bar,
)
```

however a recent tach update seems to no longer allow such ignore comments, so i had to move them to the same line as each individual import:

```py
from foo import (
    bar,  # tach-ignore
)
```

but doing so causes `tach check-external` to incorrectly report the ignore comments as unused, even though they are intended for `tach check`, not `tach check-external`:

```
> tach check-external
General
[FAIL] baz\qux.py[L2]: Ignore directive is unused.
```
