### ISSUE TITLE
Conda-forge release pinned to Python 3.9

### ISSUE THREAD

**Issue by DahnJ** [gauge-sh/tach#663]
It appears that all [conda releases](https://anaconda.org/conda-forge/tach/files) are only for Python 3.9. This means anyone on Python 3.10+ cannot install the package through Conda.

**Comment by bollwyvl** [comment]
Feedstock maintainer here: sorry for the noise! Indeed if you have a specific, well-described reproducer for your issue, please [report it on the feedstock](https://github.com/conda-forge/tach-feedstock/issues).

the recent [CEP-20](https://conda.org/learn/ceps/cep-0020/) allows for replacing the historic `{py x os x arch}` builds with just `{os x arch}` builds, similar to the [canonical `.whl` distributions](https://pypi.org/project/tach/#files). As a volunteer-run organization relying on free CI, for things that aren't absolutely using Python-version-specific features we'll probably start using this where possible.

This means _building_ against `3.9`, which is why that appears in the build string, but then the package will install and run against a non-3.9 `python`, which is tested in CI. Of note, "exotic" (e.g. not supported by Azure Pipelines) platforms are _built_ via cross-compilation/emulation, but generally cannot be fully tested.

<details>

<summary>Everything seems fine here on linux...</summary>

```yaml
# environment.yml
channels:
  - conda-forge
  - nodefaults
dependencies:
  - tach
  - python 3.13.*
```

```bash
mamba create -n foo --dry-run  --file environment.yml
```

or:

```toml
[project]
name = "tach"
platforms = ["linux-64"]
channels = ["conda-forge"]

[dependencies]
tach = "*"
python = "3.12.*"

[tasks]
tach = "tach"
```

```bash
pixi run tach init
```

</details>
