### ISSUE TITLE
Don't style text when output terminal is not interactive

### ISSUE THREAD

**Issue by pavelzw** [gauge-sh/tach#679]
When writing the report to a file, the styling doesn't get removed and results in ascii escape sequences in the file:

```
tach report my_module > report.txt
```

opening this in my IDE:

![Image](https://github.com/user-attachments/assets/18251b0f-bd3f-414d-823c-71bb8147a30d)

I would expect something like this instead (also without the warning, xref #676):

![Image](https://github.com/user-attachments/assets/b7da1272-328b-4b6a-a486-90bdc590ab62)

**Comment by pavelzw** [comment]
Basically i'm trying to build a tool that checks within my project that i only use certain external dependencies in certain submodules

```yml
allow:
  # only allow importing the `logging` module in the following submodules
  logging:
    - my_project.log
    # The below directories should be migrated in the near future.
    # We should remove each directory as they are migrated.
    - my_project.legacy
   # ...

deny:
  # Packages that exist under this tag will be denied usage
  # in precisely these modules.
  pandas:
    - my_project.new
```

The idea was to leverage `tach report --output json` (#678) and then just ensure all of these requirements are met.
But since #678 is not yet done, I planned to parse the output of `tach report` myself for now.
