### ISSUE TITLE
tach doesn't distinguish between builtin modules and my own (sub)modules

### ISSUE THREAD

**Issue by drammock** [gauge-sh/tach#685]
I have a submodule called `io`. If I define an interface for `io`, Tach is labelling imports from the Python standard library's `io` module as violations of that interface. Tach should be able to tell the difference between, e.g., `from .io import some_io_func` (package-internal) versus `from io import StringIO` (stdlib, AKA external), and not treat the latter as an interface violation.

#### Dir tree:
```
$ tree .
.
├── src
│   ├── foo.py
│   ├── __init__.py
│   └── io.py          <---- submodule mypackage.io
└── tach.toml

2 directories, 4 files
```

#### $ cat tach.toml 
```toml
source_roots = [ "src",
]

[[modules ]]
path = "io"
depends_on = []

[[modules ]]
path = "foo"
depends_on = ["io"]

[[interfaces]]
expose = ["some_io_func"]
from = ["io"]
```

#### $ cat src/__init__.py 
```
__all__ = [
    "some_foo_func",
    "some_io_func",
]

from .foo import some_foo_func
from .io import some_io_func
```

#### $ cat src/io.py 
```py
def some_io_func():
    pass
```

#### $ cat src/foo.py 
```py
from io import StringIO  # <--- builtin module io


def some_foo_func():
    pass
```

#### $ tach check
```
Interfaces
❌ src/foo.py[L1]: The path 'io.StringIO' is not part of the public interface for 'io'. [...]
```
