### ISSUE TITLE
Dependencies need to be relaxed

### ISSUE THREAD

**Issue by looztra** [gauge-sh/tach#96]
The way the dependencies of Tach are defined is very strict (only using `==`)

```toml
dependencies = [
    "pyyaml==6.0.1",
    "pydantic==2.7.1",
    "rich==13.7.1",
    "prompt-toolkit==3.0.43",
    "stdlib-list==0.10.0; python_version < '3.10'",
    "eval-type-backport==0.2.0; python_version < '3.10'"
]
```

This means that folks that want to install tach have to have these exact dependencies or it won't install.
As tach will most of the time not be installed in its own venv, this is problematic.

Could you be open to a PR that would relax the dependencies?
